# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/acy/win/dvlbuw/polymnia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/acy/win/dvlbuw/polymnia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acy/win/dvlbuw/polymnia/CMakeFiles /home/acy/win/dvlbuw/polymnia/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acy/win/dvlbuw/polymnia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named polymnia

# Build rule for target.
polymnia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 polymnia
.PHONY : polymnia

# fast build rule for target.
polymnia/fast:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/build
.PHONY : polymnia/fast

dibin.o: dibin.cpp.o
.PHONY : dibin.o

# target to build an object file
dibin.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibin.cpp.o
.PHONY : dibin.cpp.o

dibin.i: dibin.cpp.i
.PHONY : dibin.i

# target to preprocess a source file
dibin.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibin.cpp.i
.PHONY : dibin.cpp.i

dibin.s: dibin.cpp.s
.PHONY : dibin.s

# target to generate assembly for a file
dibin.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibin.cpp.s
.PHONY : dibin.cpp.s

dibout.o: dibout.cpp.o
.PHONY : dibout.o

# target to build an object file
dibout.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibout.cpp.o
.PHONY : dibout.cpp.o

dibout.i: dibout.cpp.i
.PHONY : dibout.i

# target to preprocess a source file
dibout.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibout.cpp.i
.PHONY : dibout.cpp.i

dibout.s: dibout.cpp.s
.PHONY : dibout.s

# target to generate assembly for a file
dibout.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/dibout.cpp.s
.PHONY : dibout.cpp.s

ibuf.o: ibuf.cpp.o
.PHONY : ibuf.o

# target to build an object file
ibuf.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/ibuf.cpp.o
.PHONY : ibuf.cpp.o

ibuf.i: ibuf.cpp.i
.PHONY : ibuf.i

# target to preprocess a source file
ibuf.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/ibuf.cpp.i
.PHONY : ibuf.cpp.i

ibuf.s: ibuf.cpp.s
.PHONY : ibuf.s

# target to generate assembly for a file
ibuf.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/ibuf.cpp.s
.PHONY : ibuf.cpp.s

jpegin.o: jpegin.cpp.o
.PHONY : jpegin.o

# target to build an object file
jpegin.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegin.cpp.o
.PHONY : jpegin.cpp.o

jpegin.i: jpegin.cpp.i
.PHONY : jpegin.i

# target to preprocess a source file
jpegin.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegin.cpp.i
.PHONY : jpegin.cpp.i

jpegin.s: jpegin.cpp.s
.PHONY : jpegin.s

# target to generate assembly for a file
jpegin.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegin.cpp.s
.PHONY : jpegin.cpp.s

jpegio.o: jpegio.cpp.o
.PHONY : jpegio.o

# target to build an object file
jpegio.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegio.cpp.o
.PHONY : jpegio.cpp.o

jpegio.i: jpegio.cpp.i
.PHONY : jpegio.i

# target to preprocess a source file
jpegio.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegio.cpp.i
.PHONY : jpegio.cpp.i

jpegio.s: jpegio.cpp.s
.PHONY : jpegio.s

# target to generate assembly for a file
jpegio.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegio.cpp.s
.PHONY : jpegio.cpp.s

jpegout.o: jpegout.cpp.o
.PHONY : jpegout.o

# target to build an object file
jpegout.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegout.cpp.o
.PHONY : jpegout.cpp.o

jpegout.i: jpegout.cpp.i
.PHONY : jpegout.i

# target to preprocess a source file
jpegout.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegout.cpp.i
.PHONY : jpegout.cpp.i

jpegout.s: jpegout.cpp.s
.PHONY : jpegout.s

# target to generate assembly for a file
jpegout.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/jpegout.cpp.s
.PHONY : jpegout.cpp.s

magnify.o: magnify.cpp.o
.PHONY : magnify.o

# target to build an object file
magnify.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/magnify.cpp.o
.PHONY : magnify.cpp.o

magnify.i: magnify.cpp.i
.PHONY : magnify.i

# target to preprocess a source file
magnify.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/magnify.cpp.i
.PHONY : magnify.cpp.i

magnify.s: magnify.cpp.s
.PHONY : magnify.s

# target to generate assembly for a file
magnify.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/magnify.cpp.s
.PHONY : magnify.cpp.s

picture.o: picture.cpp.o
.PHONY : picture.o

# target to build an object file
picture.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/picture.cpp.o
.PHONY : picture.cpp.o

picture.i: picture.cpp.i
.PHONY : picture.i

# target to preprocess a source file
picture.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/picture.cpp.i
.PHONY : picture.cpp.i

picture.s: picture.cpp.s
.PHONY : picture.s

# target to generate assembly for a file
picture.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/picture.cpp.s
.PHONY : picture.cpp.s

pngin.o: pngin.cpp.o
.PHONY : pngin.o

# target to build an object file
pngin.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngin.cpp.o
.PHONY : pngin.cpp.o

pngin.i: pngin.cpp.i
.PHONY : pngin.i

# target to preprocess a source file
pngin.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngin.cpp.i
.PHONY : pngin.cpp.i

pngin.s: pngin.cpp.s
.PHONY : pngin.s

# target to generate assembly for a file
pngin.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngin.cpp.s
.PHONY : pngin.cpp.s

pngout.o: pngout.cpp.o
.PHONY : pngout.o

# target to build an object file
pngout.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngout.cpp.o
.PHONY : pngout.cpp.o

pngout.i: pngout.cpp.i
.PHONY : pngout.i

# target to preprocess a source file
pngout.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngout.cpp.i
.PHONY : pngout.cpp.i

pngout.s: pngout.cpp.s
.PHONY : pngout.s

# target to generate assembly for a file
pngout.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/pngout.cpp.s
.PHONY : pngout.cpp.s

reduce.o: reduce.cpp.o
.PHONY : reduce.o

# target to build an object file
reduce.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/reduce.cpp.o
.PHONY : reduce.cpp.o

reduce.i: reduce.cpp.i
.PHONY : reduce.i

# target to preprocess a source file
reduce.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/reduce.cpp.i
.PHONY : reduce.cpp.i

reduce.s: reduce.cpp.s
.PHONY : reduce.s

# target to generate assembly for a file
reduce.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/reduce.cpp.s
.PHONY : reduce.cpp.s

to_gs_indexed.o: to_gs_indexed.cpp.o
.PHONY : to_gs_indexed.o

# target to build an object file
to_gs_indexed.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/to_gs_indexed.cpp.o
.PHONY : to_gs_indexed.cpp.o

to_gs_indexed.i: to_gs_indexed.cpp.i
.PHONY : to_gs_indexed.i

# target to preprocess a source file
to_gs_indexed.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/to_gs_indexed.cpp.i
.PHONY : to_gs_indexed.cpp.i

to_gs_indexed.s: to_gs_indexed.cpp.s
.PHONY : to_gs_indexed.s

# target to generate assembly for a file
to_gs_indexed.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/to_gs_indexed.cpp.s
.PHONY : to_gs_indexed.cpp.s

tograyscale24.o: tograyscale24.cpp.o
.PHONY : tograyscale24.o

# target to build an object file
tograyscale24.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/tograyscale24.cpp.o
.PHONY : tograyscale24.cpp.o

tograyscale24.i: tograyscale24.cpp.i
.PHONY : tograyscale24.i

# target to preprocess a source file
tograyscale24.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/tograyscale24.cpp.i
.PHONY : tograyscale24.cpp.i

tograyscale24.s: tograyscale24.cpp.s
.PHONY : tograyscale24.s

# target to generate assembly for a file
tograyscale24.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/tograyscale24.cpp.s
.PHONY : tograyscale24.cpp.s

toindexed.o: toindexed.cpp.o
.PHONY : toindexed.o

# target to build an object file
toindexed.cpp.o:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/toindexed.cpp.o
.PHONY : toindexed.cpp.o

toindexed.i: toindexed.cpp.i
.PHONY : toindexed.i

# target to preprocess a source file
toindexed.cpp.i:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/toindexed.cpp.i
.PHONY : toindexed.cpp.i

toindexed.s: toindexed.cpp.s
.PHONY : toindexed.s

# target to generate assembly for a file
toindexed.cpp.s:
	$(MAKE) -f CMakeFiles/polymnia.dir/build.make CMakeFiles/polymnia.dir/toindexed.cpp.s
.PHONY : toindexed.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... polymnia"
	@echo "... rebuild_cache"
	@echo "... dibin.o"
	@echo "... dibin.i"
	@echo "... dibin.s"
	@echo "... dibout.o"
	@echo "... dibout.i"
	@echo "... dibout.s"
	@echo "... ibuf.o"
	@echo "... ibuf.i"
	@echo "... ibuf.s"
	@echo "... jpegin.o"
	@echo "... jpegin.i"
	@echo "... jpegin.s"
	@echo "... jpegio.o"
	@echo "... jpegio.i"
	@echo "... jpegio.s"
	@echo "... jpegout.o"
	@echo "... jpegout.i"
	@echo "... jpegout.s"
	@echo "... magnify.o"
	@echo "... magnify.i"
	@echo "... magnify.s"
	@echo "... picture.o"
	@echo "... picture.i"
	@echo "... picture.s"
	@echo "... pngin.o"
	@echo "... pngin.i"
	@echo "... pngin.s"
	@echo "... pngout.o"
	@echo "... pngout.i"
	@echo "... pngout.s"
	@echo "... reduce.o"
	@echo "... reduce.i"
	@echo "... reduce.s"
	@echo "... to_gs_indexed.o"
	@echo "... to_gs_indexed.i"
	@echo "... to_gs_indexed.s"
	@echo "... tograyscale24.o"
	@echo "... tograyscale24.i"
	@echo "... tograyscale24.s"
	@echo "... toindexed.o"
	@echo "... toindexed.i"
	@echo "... toindexed.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

